### ISSUE TITLE
Složka public, podobně jako v CRA

### ISSUE THREAD

**Issue by lrolecek** [podlomar/czechitas-starter-kits#3]
Líbilo by se mi, kdybychom React starter kit byla složka `public`, jako v klasickém Create React App. 

Create Czechitas App je teď nakonfigurovaná tak, že se do `dist` kopíruje ze `src` složka `assets`, ale připadalo by mi možná jednodušší s ohledem na "kompatibilitu" s okolím světem, aby to fungovalu jako klasické CRA a další podobné starter packy. Tj. aby mimo `src` byla složka `public`, ve které by byl startovní `index.html` a zároveň by se všechno, co se do složky nakopíruje, duplikovalo při buildu 1:1 do `dist`.

Názory?

@podlomar @FilipJirsak @FilipChalupa

**Comment by FilipJirsak** [comment]
Souhlasím, složka `public` je podle mne standard a bylo by fajn, kdyby Create Czechitas App vytvářela projekty co nejpodobnější tomu, s čím se účastnice budou setkávat později.

**Comment by podlomar** [comment]
Vyřešeno v 4e274a274b9e94ad17e0a71d0d1dc1ee1d4331ee
